[package]
name = "_string_sum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "_string_sum"
crate-type = ["cdylib"]

[dependencies]
compute = "0.2.3"
pyo3 = "0.20.0"
