def sum_as_string(a: int, b: int) -> str: ...
def hello_world():
    """
    Prints "Hello, world!" to the console.
    """
    
def beta(alpha: float, beta: float) -> float: ...

def beta_n(alpha: float, beta: float, n: int) -> float: ...